# Generated by Django 4.2.10 on 2024-03-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentalapp", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile",),
    ]
