# Generated by Django 4.2.10 on 2024-03-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentalapp", "0005_speciality_resource_professional_post_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(verbose_name="last name"),
        ),
    ]
