# Generated by Django 4.2.10 on 2024-03-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentalapp", "0006_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="purpose",
            field=models.TextField(default="consultation"),
            preserve_default=False,
        ),
    ]
