# Generated by Django 4.2.10 on 2024-03-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentalapp", "0007_appointment_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="picture",
            field=models.ImageField(
                default="static/assets/default_resource_picture.jpeg",
                upload_to="static/assets/",
            ),
        ),
    ]
