# Generated by Django 4.2.10 on 2024-03-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentalapp", "0009_appointment_duration_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="mode",
            field=models.CharField(
                choices=[("Virtual", "Virtual"), ("In Person", "In Person")],
                default="In Person",
                max_length=10,
            ),
        ),
    ]
